### ISSUE TITLE
Multiple Colored belts on Student Page

### ISSUE THREAD

**Issue by curtiscali** [njc3006/TTKDSeniorProject#53]
Need to add support for non-solid belts as borders. The code for this can be accomplished as following in CSS:

```css
.my-class {
  box-shadow:
  0 0 0 6px secondary_color,
  0 0 0 12px primary_color;
}
```
